### ISSUE TITLE
Ghidra script not compatible with ghidra 10.3?

### ISSUE THREAD

**Issue by msm-cert** [mandiant/GoReSym#62]
I've noticed that after https://github.com/mandiant/GoReSym/pull/57/files the script doesn't work with my ghidra because:

```
Traceback (most recent call last):
  File "/home/msm/ghidra_scripts/goresym.py", line 206, in <module>
    choices_dict, suggested = offset_estimation_sim(hints)
  File "/home/msm/ghidra_scripts/goresym.py", line 189, in offset_estimation_sim
    renamed, created = rename_funcs(hfuncs, estoff, True)
  File "/home/msm/ghidra_scripts/goresym.py", line 143, in rename_funcs
    fm = currentProgram().getFunctionManager()
TypeError: 'ghidra.program.database.ProgramDB' object is not callable
```

Note: I'm using Ghidra 10.3 from May 2023, it's possible that this problem doesn't occur in newer versions.

**Comment by stevemk14ebr** [comment]
Can you confirm it doesn't work on the latest ghidra?

**Comment by TheEquus** [comment]
It seems like the changes made to make the Ghidra script compatible with Ghidrathon (`currentProgram -> currentProgram()`) made the script break with Ghidra's jython, since the function doesn't exist natively. 

If you're using Ghidra without Ghidrathon you can just change it back to `currentProgram` locally. But maybe to make it compatible with both, you could try replacing it with `getCurrentProgram()`?

**Comment by stevemk14ebr** [comment]
I'd love to accept a PR that fixes the script to be more compatible
